postgres:
  image: postgres:9.6-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'tictactoe'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/
